import { basenameOf } from './provider-support.js';

const GENERATED_HEADER =
  /(?:@generated\b|code generated by|this file (?:was|is) (?:auto[- ]?)generated|do not edit|autogenerated by)/iu;
const GENERATED_PATH =
  /(?:^|\/)(?:__generated__|\.generated|generated\/|\.pb\/)|\.(?:pb\.go|pb\.cc|pb\.h|pb\.ts|pb\.js|pb2\.py)$/iu;
const GENERATED_NAME = /(?:_pb2|_grpc_pb|_generated|\.g|\.designer)\.[A-Za-z0-9]+$/u;

/**
 * Conservative generated-source detector. Inventory stays. Generated files are
 * indexed for unique authored-call targets; unreferenced internals are not
 * materialized as symbols. Call binding treats generated symbols as unique
 * targets only — they never collide with authored names in the candidate index.
 */
export function isGeneratedSource(locator: string, source: string): boolean {
  const name = basenameOf(locator);
  if (GENERATED_PATH.test(locator) || GENERATED_NAME.test(name)) return true;
  return GENERATED_HEADER.test(source.slice(0, 4096));
}
