export {
  WIS_CORE_CONTRACT_VERSION,
  WIS_COMPATIBILITY_STATUSES,
  WIS_DIAGNOSTIC_SEVERITIES,
  WIS_OPERATION_OUTCOMES,
  WIS_RESULT_STATUSES,
  WIS_SCOPE_KINDS,
  defineWisContract,
  type WisArtifactReference,
  type WisCompatibilityStatus,
  type WisCompatibilitySummary,
  type WisContractReference,
  type WisDiagnostic,
  type WisDiagnosticSeverity,
  type WisDigestReference,
  type WisEvidenceReference,
  type WisFreshnessStatus,
  type WisFreshnessSummary,
  type WisGenerationReference,
  type WisOmission,
  type WisOperationOutcome,
  type WisOrganizationScopeReference,
  type WisProfileReference,
  type WisProjectScopeReference,
  type WisProducerReference,
  type WisRenewalReference,
  type WisResultEnvelope,
  type WisResultStatus,
  type WisScopeReference,
  type WisSelectionScopeReference,
  type WisUnknownRecord,
  type WisWorkspaceScopeReference,
} from './core.js';
export type { WisContractCatalog } from '../generated/wis-contract-catalog.js';
