import { defineWisContract } from '@workspai/shared/contracts';

export const GRAPH_PACKAGE_STATUS_CONTRACT = defineWisContract({
  id: 'workspai.graph.package-status',
  version: '0.1.0-draft',
});

export const GRAPH_PACKAGE_MATURITY = 'repository-preview-candidate' as const;

export const GRAPH_PACKAGE_METADATA = Object.freeze({
  name: '@workspai/graph',
  version: '0.0.0-development',
  maturity: GRAPH_PACKAGE_MATURITY,
  publishable: false,
  implementedCapabilities: [
    'package-status',
    'shared-adoption-conformance',
    'entity-identity-contract-candidate',
    'provider-manifest-contract-candidate',
    'provider-detection-contract-candidate',
    'fact-batch-contract-candidate',
    'foundation-semantic-admission',
    'provider-output-admission',
    'generated-wire-types',
    'content-addressed-contract-catalog',
    'portable-identity-normalization',
    'ontology-semantic-admission',
    'canonical-graph-semantic-admission',
    'generation-publication-semantic-admission',
    'graph-model-generation-binding-admission',
    'quality-semantic-admission',
    'query-cache-lifecycle-semantic-admission',
    'optional-query-cache-store',
    'bounded-canonical-digest-replay',
    'evidence-independence-assessment',
    'deterministic-reference-composition',
    'evidence-backed-proof-evaluation',
    'functional-conflict-preservation',
    'graph-quality-assessment',
    'injected-execution-ports',
    'validated-worker-output-accounting',
    'node-reference-worker-adapter',
    'non-publishable-cancellation',
    'versioned-proof-policy-assessment',
    'cross-layer-binding-profiles',
    'deterministic-proof-carrying-query',
    'bounded-query-planning',
    'deterministic-query-pagination',
    'operational-risk-abstention',
    'query-result-semantic-admission',
    'query-scale-baseline',
    'governed-repository-build-orchestration',
    'bounded-repository-file-inventory-port',
    'official-offline-repository-providers',
    'node-repository-preview-adapter',
    'repository-contract-runtime-delivery-surfaces',
    'compose-service-dependency-topology',
    'codeowners-file-ownership',
    'cross-language-source-entrypoints',
    'matlab-artifact-surfaces',
    'safe-local-git-head-evidence',
    'declarative-structural-extractor-profile',
    'literal-route-extraction',
    'unsupported-language-abstention',
    'multi-language-repository-fixtures',
    'fixed-repository-preview-views',
    'bounded-review-context-slice',
    'project-local-atomic-persistence',
    'explicit-generation-publication',
    'standalone-executable',
    'installed-cli-smoke',
    'honest-incremental-execution-accounting',
    'scan-profile-merkle-leaf-identity',
    'executed-canonical-generation-delta',
    'query-cache-store-invalidation',
    'merkle-unequal-branch-walk',
    'semantic-dependency-shard-invalidation',
    'observation-excluded-merkle-identity',
    'git-nongit-incremental-digest-parity',
    'official-provider-incremental-equivalence',
    'similarity-barred-from-canonical-reuse',
    'added-input-provider-reobservation',
    'nfc-portable-content-locators',
    'official-cross-language-incremental-mutations',
    'profile-driven-projection',
    'workspace-graph-composition',
    'incremental-engine',
    'proposed-change-overlay',
    'standalone-cli-json-contract',
    'standalone-support-matrix',
    'cyclonedx-sbom-candidate',
    'synthetic-retrieval-benchmark',
    'packed-artifact-security-scan',
    'internal-promotion-inventory-candidate',
    'packed-conformance-corpus',
    'incident-rollback-boundary-candidate',
    'packed-version-1-query-preset-jobs',
    'packed-installed-product-corpus',
    'partial-cli-exit-code-integrity',
    'rust-wasm-traversal-conformance-candidate',
  ] as const,
  plannedCapabilities: ['standalone-stable', 'cli-shadow-parity'] as const,
});

export type GraphPackageMetadata = typeof GRAPH_PACKAGE_METADATA;
